version: '3'
services:
  db:
    image: neo4j
    volumes:
      - ./db/data:/data
    ports:
      - "7474:7474"
      - "7687:7687"
    env_file:
      - .env
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
